// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iiwi.Database;

#nullable disable

namespace iiwi.Database.Migrations.Seeds
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102162352_SeedPermissions")]
    partial class SeedPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", "Identity");
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Identity");
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", "Identity");
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Claims", "Identity");
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("Logins", "Identity");
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", "Identity");
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Identity");
                });

            modelBuilder.Entity("iiwi.Domain.Logs.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChangedData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ChangedDataJson");

                    b.Property<string>("EntityName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("EventTimestamp");

                    b.HasKey("Id");

                    b.ToTable("Audit", "Log");
                });

            modelBuilder.Entity("iiwi.Domain.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("Permission", "Identity");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CodeName = "TEST.READ",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test.Read",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2L,
                            CodeName = "TEST.CREATE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test.Create",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3L,
                            CodeName = "TEST.UPDATE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test.Update",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4L,
                            CodeName = "TEST.DELETE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test.Delete",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5L,
                            CodeName = "ACCOUNT.READ",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.Read",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6L,
                            CodeName = "ACCOUNT.CREATE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.Create",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7L,
                            CodeName = "ACCOUNT.UPDATE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.Update",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8L,
                            CodeName = "ACCOUNT.DELETE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.Delete",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9L,
                            CodeName = "ACCOUNT.UPDATEPROFILE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.UpdateProfile",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10L,
                            CodeName = "ACCOUNT.DELETEPERSONALDATA",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.DeletePersonalData",
                            IsActive = true
                        },
                        new
                        {
                            Id = 11L,
                            CodeName = "ACCOUNT.DOWNLOADINFO",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.DownloadInfo",
                            IsActive = true
                        },
                        new
                        {
                            Id = 12L,
                            CodeName = "ACCOUNT.SENDVERIFICATIONDETAILS",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.SendVerificationDetails",
                            IsActive = true
                        },
                        new
                        {
                            Id = 13L,
                            CodeName = "ACCOUNT.CHANGEEMAIL",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.ChangeEmail",
                            IsActive = true
                        },
                        new
                        {
                            Id = 14L,
                            CodeName = "ACCOUNT.UPDATEPHONENUMBER",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Account.UpdatePhoneNumber",
                            IsActive = true
                        },
                        new
                        {
                            Id = 15L,
                            CodeName = "AUTHENTICATION.READ",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.Read",
                            IsActive = true
                        },
                        new
                        {
                            Id = 16L,
                            CodeName = "AUTHENTICATION.CREATE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.Create",
                            IsActive = true
                        },
                        new
                        {
                            Id = 17L,
                            CodeName = "AUTHENTICATION.UPDATE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.Update",
                            IsActive = true
                        },
                        new
                        {
                            Id = 18L,
                            CodeName = "AUTHENTICATION.DELETE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.Delete",
                            IsActive = true
                        },
                        new
                        {
                            Id = 19L,
                            CodeName = "AUTHENTICATION.LOADKEYANDQRCODEURI",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.LoadKeyAndQrCodeUri",
                            IsActive = true
                        },
                        new
                        {
                            Id = 20L,
                            CodeName = "AUTHENTICATION.EXTERNALLOGINS",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.ExternalLogins",
                            IsActive = true
                        },
                        new
                        {
                            Id = 21L,
                            CodeName = "AUTHENTICATION.REMOVELOGIN",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.RemoveLogin",
                            IsActive = true
                        },
                        new
                        {
                            Id = 22L,
                            CodeName = "AUTHENTICATION.LINKLOGIN",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.LinkLogin",
                            IsActive = true
                        },
                        new
                        {
                            Id = 23L,
                            CodeName = "AUTHENTICATION.LINKLOGINCALLBACK",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.LinkLoginCallback",
                            IsActive = true
                        },
                        new
                        {
                            Id = 24L,
                            CodeName = "AUTHENTICATION.GENERATERECOVERYCODES",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.GenerateRecoveryCodes",
                            IsActive = true
                        },
                        new
                        {
                            Id = 25L,
                            CodeName = "AUTHENTICATION.RESETAUTHENTICATOR",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.ResetAuthenticator",
                            IsActive = true
                        },
                        new
                        {
                            Id = 26L,
                            CodeName = "AUTHENTICATION.SETPASSWORD",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.SetPassword",
                            IsActive = true
                        },
                        new
                        {
                            Id = 27L,
                            CodeName = "AUTHENTICATION.CHANGEPASSWORD",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.ChangePassword",
                            IsActive = true
                        },
                        new
                        {
                            Id = 28L,
                            CodeName = "AUTHENTICATION.ACCOUNTSTATUS",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.AccountStatus",
                            IsActive = true
                        },
                        new
                        {
                            Id = 29L,
                            CodeName = "AUTHENTICATION.FORGOTBROWSER",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.ForgotBrowser",
                            IsActive = true
                        },
                        new
                        {
                            Id = 30L,
                            CodeName = "AUTHENTICATION.DISABLE2FA",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentication.Disable2fa",
                            IsActive = true
                        },
                        new
                        {
                            Id = 31L,
                            CodeName = "AUTHORIZATION.READ",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.Read",
                            IsActive = true
                        },
                        new
                        {
                            Id = 32L,
                            CodeName = "AUTHORIZATION.CREATE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.Create",
                            IsActive = true
                        },
                        new
                        {
                            Id = 33L,
                            CodeName = "AUTHORIZATION.UPDATE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.Update",
                            IsActive = true
                        },
                        new
                        {
                            Id = 34L,
                            CodeName = "AUTHORIZATION.DELETE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.Delete",
                            IsActive = true
                        },
                        new
                        {
                            Id = 35L,
                            CodeName = "AUTHORIZATION.ALLROLES",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.AllRoles",
                            IsActive = true
                        },
                        new
                        {
                            Id = 36L,
                            CodeName = "AUTHORIZATION.ADDROLE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.AddRole",
                            IsActive = true
                        },
                        new
                        {
                            Id = 37L,
                            CodeName = "AUTHORIZATION.UPDATEROLE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.UpdateRole",
                            IsActive = true
                        },
                        new
                        {
                            Id = 38L,
                            CodeName = "AUTHORIZATION.DELETEROLE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.DeleteRole",
                            IsActive = true
                        },
                        new
                        {
                            Id = 39L,
                            CodeName = "AUTHORIZATION.ROLESBYID",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.RolesById",
                            IsActive = true
                        },
                        new
                        {
                            Id = 40L,
                            CodeName = "AUTHORIZATION.ADDCLAIM",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.AddClaim",
                            IsActive = true
                        },
                        new
                        {
                            Id = 41L,
                            CodeName = "AUTHORIZATION.ADDROLECLAIM",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.AddRoleClaim",
                            IsActive = true
                        },
                        new
                        {
                            Id = 42L,
                            CodeName = "AUTHORIZATION.REMOVEROLECLAIM",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.RemoveRoleClaim",
                            IsActive = true
                        },
                        new
                        {
                            Id = 43L,
                            CodeName = "AUTHORIZATION.GETROLECLAIMS",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.GetRoleClaims",
                            IsActive = true
                        },
                        new
                        {
                            Id = 44L,
                            CodeName = "AUTHORIZATION.ASSIGNROLE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.AssignRole",
                            IsActive = true
                        },
                        new
                        {
                            Id = 45L,
                            CodeName = "AUTHORIZATION.ASSIGNROLE",
                            CreationDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authorization.AssignRole",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationRoleClaim", b =>
                {
                    b.HasOne("iiwi.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUserClaim", b =>
                {
                    b.HasOne("iiwi.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUserLogin", b =>
                {
                    b.HasOne("iiwi.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("iiwi.Domain.Identity.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iiwi.Domain.Identity.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUserToken", b =>
                {
                    b.HasOne("iiwi.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("iiwi.Domain.Permission", b =>
                {
                    b.HasOne("iiwi.Domain.Identity.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("iiwi.Domain.Identity.ApplicationUser", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("iiwi.Domain.Identity.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("iiwi.Domain.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
